@startmindmap
* Projekte
** Fitness
*** Aldesoky Abdullah 3
** web-Crawler (Faktenfinder) -4
*** Aichinger Tobias
**[#Orange] Restaurant - Bestellsystem
*** Salkovic Armin
** Haushalts-Inventar-App
*** Gruber Moritz
** Open-World 2D game
*** Berg Bajtik
** Künstlerdatenbank
*** Balazs Balint
** Terminkalender
*** Cao Anton
** 2D Shooter Game
*** Csomany Axel
*** Nikolaus Alexander
**[#Orange] Scoring App für Darts
*** Seifried Erik
** Vorratchecker
*** Lehner David
** Daily Finance
*** Fröller Felix
** online-email-verteiler
*** Schnalzenberger Arwed
** Paketmanager für Win
*** Schludermann Julian
**[#Orange] Moped-Meetup
*** Nestler Linus
** jump-n-run
*** Cvijic Luka
** Zeichenprogramm
*** Breinesberger Markus
** Nachrichtenapp
*** Daxinger Oliver
** Fussball-Statistik
*** Nurceski Said
** AirQual
*** Saydam Arda
**[#Orange] Kalorienrechner
*** Stroschneider Fabian 1
** n/a
*** Sukhbath Munkh 5
** Spiel
*** Sonnleitner Lukas
**[#Orange] Kurstermine
*** Ilming Winnie








@endmindmap
