@startmindmap
* Projekte
**[#Orange] Restaurant - Bestellsystem
***[#yellow] Salkovic Armin 1
*** Sukhbat Munkh 5
*** Balazs Balint 2
*** Aldesoky Abdullah 3
**[#Orange] Scoring App für Darts
***[#yellow] Seifried Erik 4
*** Csomany Axel 4
*** Nikolaus Alexander 3
*** Cvijic Luka 2
**[#Orange] Vorratschecker
***[#yellow] Lehner David 1
*** Saydam Arda 4
*** Fröller Felix 1
*** Cao Anton 1
**[#Orange] Moped-Meetup
***[#yellow] Nestler Linus 1
*** Nurceski Said 2
*** Daxinger Oliver 3
*** Berg Bajtik 2
**[#Orange] Kalorienrechner
***[#yellow] Stroschneider Fabian 4
*** Breinesberger Markus 1
*** Gruber Moritz 1
*** Aichinger Tobias 1
**[#Orange] Kurstermine
***[#yellow] Ilming Winnie 1
*** Sonnleitner Lukas 1
*** Schludermann Julian 1
*** Schnalzenberger Arwed 1








@endmindmap
